name: Docker Image CI

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      TAG_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Tag Docker image for GitHub Container Registry
        run: |
          docker tag ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest ghcr.io/${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest
          docker tag ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest ghcr.io/${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:${{ env.TAG_NAME }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest
          docker push ghcr.io/${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:${{ env.TAG_NAME }}
