name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker push ${{ env.DOCKER_USERNAME }}/octopus-usage-exporter:latest
      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Tag Docker image for GitHub Container Registry
        env:
          IMAGE_REPOSITORY: ${{ env.IMAGE_REPOSITORY }}
        run: docker tag ${{ IMAGE_REPOSITORY }}/octopus-usage-exporter:latest ghcr.io/${{ IMAGE_REPOSITORY }}:latest
      - name: Push Docker image to GitHub Container Registry
        env:
          IMAGE_REPOSITORY: ${{ env.IMAGE_REPOSITORY }}
        run: docker push ghcr.io/${{ IMAGE_REPOSITORY }}:latest
